### PR TITLE
Fix - HTML5 drag and drop with dataTransfer does not work in Chrome, …

### PR DESCRIPTION
**Pull request by juansieira**
…use localStorage instead

### CODE REVIEW

**Comment by jajm** [comment]
Which version of Chrome are you using ? I just tested with Chrome 81.0.4044.129 and I have no problem with drag and drop.

**Comment by juansieira** [comment]
> Which version of Chrome are you using ? I just tested with Chrome 81.0.4044.129 and I have no problem with drag and drop.

We're using 81.0.4044.138 on Mac OSX, and I tested on two different laptobs, both Mac

**Comment by jajm** [comment]
I don't have a Mac OSX system so I can't test, but it may have something to do with the MIME type. Can you try replacing `application/vnd.urungi.filter-prompt+json` by `application/json` and see if it works ?

**Comment by juansieira** [comment]
> I don't have a Mac OSX system so I can't test, but it may have something to do with the MIME type. Can you try replacing `application/vnd.urungi.filter-prompt+json` by `application/json` and see if it works ?

I've starting testing only with the DnD on layouts, so there is only text/html . I've tested with:
"text"
"text/plain"

and nothing happens, it never save the html content into the dataTransfer.

With Firefox on Mac I have no problems.

**Comment by juansieira** [comment]
> I don't have a Mac OSX system so I can't test, but it may have something to do with the MIME type. Can you try replacing `application/vnd.urungi.filter-prompt+json` by `application/json` and see if it works ?

Hello Julian. On DragStart, after saving the content in dataTransfer, I can get the data. But this this information is not available onDrop. If it helps ..

**Pull request closed without merging**
